### ISSUE TITLE
feature request: Support optional "name" for Runtime manifest file

### ISSUE THREAD

**Issue by utzcoz** [rpavlik/xr-picker#27]
From https://registry.khronos.org/OpenXR/specs/1.0/loader.html#active-runtime-information, 5.1.2. Runtime Enumeration
, there is a statement:

> Runtime manifest files may optionally contain a "name" field. Tools that allow users to configure what runtime is currently active should display this user-friendly name if present when referring to the runtime in question.

If the third-party declares the `name` field in Runtime manifest file, the xr-picker can show this name for manual added Runtime manifest file. And some fixed/predefined Runtime name can be moved into their Runtime manifest file with "name" field.

**Comment by rpavlik** [comment]
I think it already does that, doesn't it?  See the screenshot. You can't specify the name of one that is missing that field, but it should be using it...

**Comment by utzcoz** [comment]
@rpavlik Thanks for your clarifing. I update my testing manifest json file, and it works fine to show its name. It works great. Thanks for your tool to support it.
